DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS Petitions;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS USER_ROLES;

CREATE TABLE USER (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  email TEXT NOT NULL,
  is_active INTEGER DEFAULT 1,
  role INTEGER NOT NULL DEFAULT 1,
  FOREIGN KEY(id) REFERENCES ROLE(id)
);

CREATE TABLE Petitions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES USER (id)
);

CREATE TABLE ROLE(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE
);

CREATE TABLE USER_ROLES(
  id INTEGER PRIMARY KEY,
  user_id INTEGER,
  role_id INTEGER,
  FOREIGN KEY (user_id) REFERENCES USER (id),
  FOREIGN KEY (role_id) REFERENCES ROLE (id)
 );